name: Run Jupyter Notebook

on:
  push:
    branches:
      - premier  # Change this to your main branch

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute logreg.ipynb

